openapi: "3.0.0"
info:
  title: "Wutsi QR API"
  description: |
    API for generating QR Code.

  version: "1.0.0"

servers:
  - url: https://wutsi-qr-server-test.herokuapp.com
    description: Sandbox
  - url: https://wutsi-qr-server-prod.herokuapp.com
    description: Production

paths:
  /v1/account:
    post:
      operationId: "account"
      description: |
        Create a QR code token for the current user.
        The format is `account:<account-id>:<expiry-time>`

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountQRCodeResponse'
      tags:
        - QR
      security:
        - api_key: [ 'qr-manage' ]

  /v1/payment:
    post:
      operationId: "payment"
      description: |
        Create a QR code token for a payment request.
        The format is `payment:<merchant-id>:<reference-id>:<amount>:<currency>:<expiry-time>`

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentQRCodeRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePaymentQRCodeResponse'
      tags:
        - QR
      security:
        - api_key: [ 'qr-manage' ]


components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    CreatePaymentQRCodeRequest:
      type: object
      properties:
        referenceId:
          type: string
          format: uuid
          description: Unique identifier of the request
        merchantId:
          type: integer
          format: int64
          description: Merchant Account ID
        amount:
          type: number
          format: double
          description: Amount of the order
          minimum: 0
        currency:
          type: string
          description: 3 letter currency code
          maxLength: 3
        timeToLive:
          type: integer
          description: Time-To-Live of the QR code
          nullable: true
      required:
        - currency
        - referenceId

    CreatePaymentQRCodeResponse:
      type: object
      properties:
        token:
          type: string
          description: QR Code Token


    CreateAccountQRCodeResponse:
      type: object
      properties:
        token:
          type: string
          description: QR Code Token
